name: Python

on: [push]

jobs:
  CI:
    name: Python CI
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: poetry  
    - name: Install project dependencies
      run: poetry install
    - name: Ruff Linting
      run: poetry run ruff check --output-format=github
    - name: Pytest
      run: poetry run pytest -v tests --junitxml=test-results.xml --cov=src/python --cov-report=xml --cov-report=html --cov-report=json
      if: always()
    - name: Generate summaries
      uses: test-summary/action@v2
      with:
        paths: "*-results.xml"
        show: all
      if: always()
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: htmlcov
